#SPDX-License-Identifier: MIT-0
---
# vars file for roles/tmpl

nfile_d: 10000
nfile_cs: 1000

utenti:
  - alice
  - bob
  - carol
  - dave

from_image: python:3.11-slim
author: alessiohajdini
workdir: /app