Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt update
     sudo apt install -y ansible
     sudo apt install -y docker.io
     sudo usermod -aG docker vagrant
  SHELL
  
#  config.vm.provision "ansible" do |ansible|
#      ansible.playbook =  "./Prove.yaml" 
#      ansible.become = true
#  end

  config.vm.provider "virtualbox" do |v|
      v.cpus = "1"
      v.memory = "1024"
      v.linked_clone= false
  end

  config.vm.define "m1" do |m1|
      m1.vm.hostname = "m1"
      m1.vm.provider "virtualbox" do |v|
          v.cpus = "2"
          v.memory = "2048"
          v.linked_clone= false
      end
      m1.vm.network "private_network" , ip: "192.168.3.104"
  end

  config.vm.define "m2" do |m2|
      m2.vm.hostname = "m2"
      m2.vm.network "private_network" , ip: "192.168.3.105"     
  end
end
