
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  
  
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y docker.io
     sudo usermod -aG docker vagrant
  SHELL
  
  config.vm.provider "virtualbox" do |v|
      v.cpus = "1"
      v.memory = "1024"
      v.linked_clone= false
  end

  config.vm.define "m1" do |m1|
      m1.vm.hostname = "m1"
      m1.vm.network "private_network" , ip: "192.168.1.2"
  end

  config.vm.define "m2" do |m2|
      m2.vm.hostname = "m2"
      m2.vm.network "private_network" , ip: "192.168.1.3"     
  end
end
