- name: installazione Minikube K8s e jenkins e docker
  hosts: all
  become: true
  tasks:
  
  - name: installazion docker
    apt: 
      name: 
        - docker.io
        - python3-pip
      state: present
      update_cache: yes
      
  - name: installazione dipendenza python
    pip:
      name: docker
      state: present
      
  - name: installazione Minikube
    get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      dest: /usr/local/bin/minikube
      mode: 0755
      
  - name: versione stabile kubectl
    uri:
      url: https://dl.k8s.io/release/stable.txt
      return_content: yes
    register: kubectl_version
  
  - name: installazione kubectl 2
    get_url:
      url: https://dl.k8s.io/release/{{ kubectl_version.content | trim }}/bin/linux/amd64/kubectl
      dest: /usr/local/bin/kubectl
      mode: 0755
      
  - name: creazione rete docker per jenkins
    community.docker.docker_network:
      name: jenkins_rete
      ipam_config:
        - subnet: 172.10.0.0/24
          gateway: 172.10.0.1
      state: present
      
  - name: jenkins docker
    community.docker.docker_container:
      name: jenkins
      image: jenkins/jenkins:lts
      state: started
      recreate: yes
      force_kill: yes
      restart_policy: always
      networks:
        - name: jenkins_rete
          ipv4_address: 172.10.0.10
      ports:
        - 8080:8080
        - 50000:50000
      volumes:
        - jenkins_home:/var/jenkins_home
    
    
