- name: installazione Minikube,K8s,jenkins,jenkins_agent e docker
  hosts: all
  become: true
  tasks:
  
  - name: installazion docker
    apt: 
      name: 
        - docker.io
        - python3-pip
      state: present
      update_cache: yes
      
  - name: permessi jenkins
    file:
      path: /var/jenkins_home
      owner: 1000
      group: 1000
      mode: 0755
      recurse: yes
      state: directory
    
  - name: directory agent
    file:
      path: /home/jenkins/agent
      owner: 1000
      group: 1000
      state: directory
      mode: 0755
      recurse: yes
      
  - name: installazione dipendenza python
    pip:
      name: docker
      state: present
      
  - name: installazione Minikube
    get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      dest: /usr/local/bin/minikube
      mode: 0755
      
  - name: versione stabile kubectl
    uri:
      url: https://dl.k8s.io/release/stable.txt
      return_content: yes
    register: kubectl_version
  
  - name: installazione kubectl 2
    get_url:
      url: https://dl.k8s.io/release/{{ kubectl_version.content | trim }}/bin/linux/amd64/kubectl
      dest: /usr/local/bin/kubectl
      mode: 0755
      
  - name: creazione rete docker per jenkins
    community.docker.docker_network:
      name: jenkins_rete
      ipam_config:
        - subnet: 172.10.0.0/24
          gateway: 172.10.0.1
      state: present
      
  - name: jenkins docker
    community.docker.docker_container:
      name: jenkins
      image: jenkins/jenkins:lts
      state: started
      recreate: yes
      force_kill: yes
      restart_policy: always
      networks:
        - name: jenkins_rete
          ipv4_address: 172.10.0.10
      ports:
        - 8080:8080
        - 50000:50000
      volumes:
        - /var/jenkins_home:/var/jenkins_home
        
  - name: check jenkins
    uri:
      url: http://192.168.3.104:8080/login
      status_code: 200
    register: status
    until: status.status == 200
    retries: 5
    delay: 3
    
  - name: setup agent
    community.general.jenkins_script:
      url: http://192.168.3.104:8080
      user: admin
      password: "{{password}}"
      script: |
        import jenkins.model.*
        import hudson.slaves.*

        def jenkins = Jenkins.instance

        if (!jenkins.getNode("agent1")) {
          def launcher = new JNLPLauncher(true)
          def agent = new DumbSlave(
            "agent1",
            "/home/jenkins/agent",
            launcher
          )
          agent.numExecutors = 2
          agent.labelString = "linux"
          jenkins.addNode(agent)
          jenkins.save()
        }
        
  - name: recupero secret dell'agent
    community.general.jenkins_script:
      url: http://192.168.3.104:8080
      user: admin
      password: "{{password}}"
      script: |
        println jenkins.model.Jenkins.instance
        .getComputer("agent1")
        .getJnlpMac()
    register: secret
      
  - name: estrazione secret
    set_fact:
      agent_secret: "{{ secret.output | regex_replace('Result: ', '') | trim }}"
  
  - name: setup agent jenkins
    community.docker.docker_container:
      name: agent1
      image: jenkins/inbound-agent:latest
      state: started
      restart_policy: always
      env:
        JENKINS_SECRET: "{{ agent_secret }}"
        JENKINS_AGENT_NAME: agent1
        JENKINS_URL: http://172.10.0.10:8080
        JENKINS_AGENT_WORKDIR: /home/jenkins/agent
      networks:
        - name: jenkins_rete
          ipv4_address: 172.10.0.11