- name: installazione Minikube,K8s,jenkins,jenkins_agent e docker
  hosts: all
  become: true
  tasks:

  roles:
    - docker
    - permessi_cartelle
    - minikube
    - kubectl
    - jenkins_master
    - check_jenkins
    - jenkins_agent