- name: aggiornamento sistema
  hosts: all
  become: true
  tasks:
  - name: creazione gruppo Parigi
    group:
      name: Parigi
      state: present
      gid: 1500
  - name: creazione gruppo Tokyo
    group:
      name: Tokyo
      state: present
      gid: 1501
  - name: creazione gruppo NewYork
    group:
      name: NewYork
      state: present
      gid: 1502