#SPDX-License-Identifier: MIT-0
---
# tasks file for role/jenkins_master

- name: jenkins master
  community.docker.docker_container:
    name: jenkins
    image: "{{ jenkins_image }}"
    state: started
    restart_policy: always
    groups:
      - "119"
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - name: "{{ jenkins_network_name }}"
        ipv4_address: "{{ jenkins_master_docker_ip }}"
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker