#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/restore

- name: restore database mariadb
  ansible.builtin.shell:
    cmd: "mariadb < /tmp/{{ db_name }}.sql"
  when: inventory_hostname == "m2"