Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.ssh.insert_key = false
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y mariadb-server
    sudo systemctl enable mariadb
    sudo systemctl start mariadb
  SHELL

  config.vm.provider "virtualbox" do |v|
      v.cpus = "1"
      v.memory = "1024"
      v.linked_clone= false
  end

  config.vm.define "db1" do |m1|
      m1.vm.hostname = "m1"
      m1.vm.provider "virtualbox" do |v|
          v.cpus = "1"
          v.memory = "2048"
          v.linked_clone= false
      end
      m1.vm.network "private_network" , ip: "192.168.56.104"
      m1.vm.network "forwarded_port", guest: 22, host: 2223, host_ip: "0.0.0.0"
  end

  config.vm.define "db2" do |m2|
      m2.vm.hostname = "m2"
      m2.vm.provider "virtualbox" do |a|
          a.cpus = "1"
          a.memory = "2048"
          a.linked_clone = false
      end
      m2.vm.network "private_network" , ip: "192.168.56.105"
      m2.vm.network "forwarded_port", guest: 22, host: 2224, host_ip: "0.0.0.0"
  end
end