#SPDX-License-Identifier: MIT-0
---
# tasks file for role/kubectl

- name: versione stabile kubectl
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_version

- name: installazione kubectl 2
  get_url:
    url: https://dl.k8s.io/release/{{ kubectl_version.content | trim }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755