Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt update
     sudo apt install -y docker.io
     sudo usermod -aG docker vagrant
     echo "DNS=8.8.8.8 1.1.1.1" | sudo tee -a /etc/systemd/resolved.conf
     sudo systemctl restart systemd-resolved
  SHELL

  config.vm.provider "virtualbox" do |v|
      v.cpus = "1"
      v.memory = "1024"
      v.linked_clone= false
  end

  config.vm.define "m1" do |m1|
      m1.vm.hostname = "m1"
      m1.vm.provider "virtualbox" do |v|
          v.cpus = "2"
          v.memory = "4096"
          v.linked_clone= false
      end
      m1.vm.network "private_network" , ip: "192.168.56.104"
  end

  config.vm.define "m2" do |m2|
      m2.vm.hostname = "m2"
      m2.vm.provider "virtualbox" do |a|
          a.cpus = "2"
          a.memory = "2048"
          a.linked_clone = false
      end
      m2.vm.network "private_network" , ip: "192.168.56.105"
  end
end
