#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/tmpl
- name: templating limit
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
- name: templating access
  template:
    src: access.conf.j2
    dest: /etc/security/access.conf
- name: templating dockerfile
  template:
    src: Dockerfile.j2
    dest: /tmp/Dockerfile