#SPDX-License-Identifier: MIT-0
---
# tasks file for role/minikube

- name: installazione Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: 0755