#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/backup

- name: backup database mariadb
  ansible.builtin.shell:
    cmd: "mariadb-dump -u {{ db_user }} -p{{ db_password }} --databases {{ db_name }} > /tmp/{{ db_name }}.sql"
  no_log: true
  when: inventory_hostname == "m1"

- name: trasferimento backup
  ansible.builtin.fetch:
    src: "/tmp/{{ db_name }}.sql"
    dest: "/tmp/{{ db_name }}.sql"
    flat: true
  when: inventory_hostname == "m1"
