#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/backup

- name: backup database mariadb
  ansible.builtin.shell:
    cmd: "mariadb-dump --databases {{ db_name }} > /tmp/{{ db_name }}.sql"
  when: inventory_hostname == "m1"

- name: trasferimento backup
  ansible.builtin.shell:
    cmd: "scp /tmp/{{ db_name }}.sql vagrant@{{hostvars['m2'].ansible_host}}:/tmp/{{ db_name }}.sql"
  when: inventory_hostname == "m1"

